AWSTemplateFormatVersion: "2010-09-09"
Description: AWS::DynamoDB - {{ component_name }} - security items

Resources:
  # Application autoscaling role
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
        Version: "2012-10-17"
      Path: "/"
      Policies:
        - PolicyName: base
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:UpdateTable
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:GetMetricStatistics
                  - cloudwatch:SetAlarmState
                  - cloudwatch:DeleteAlarms
                Resource: '*'

Outputs:
  DefaultExport:
    Value:
      Ref: AWS::StackName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:DefaultExport"

  RoleArn:
    Value:
      Fn::GetAtt: [ Role, Arn ]
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:RoleArn"

  RoleName:
    Value:
      Ref: Role
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:RoleName"
