AWSTemplateFormatVersion: "2010-09-09"
Description: AWS::RDS::Aurora - {{ component_name }} - security items

Resources:
  MonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - monitoring.rds.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole
      Path: "/"

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group
      VpcId:
        Fn::ImportValue: "{{ context.ResourceNamespace | d('core-network') }}:{{ context.VpcAliases['private'] }}:VpcId"

Outputs:
  DefaultExport:
    Value:
      Ref: AWS::StackName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:DefaultExport"

  SecurityGroupId:
    Value:
      Ref: SecurityGroup
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:SecurityGroupId"

  MonitoringRoleName:
    Value:
      Ref: MonitoringRole
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:MonitoringRoleName"

  MonitoringRoleArn:
    Value:
      Fn::GetAtt: [ MonitoringRole, Arn ]
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:MonitoringRoleArn"

