{% import "AWS/_shared/vars/names.j2" as names with context %}

{% set Build = context.Build %}
{% if 'PersistUpdateVersion' in app[component_name] %}
{% set Build = app[component_name].PersistUpdateVersion %}
{% endif %}

AWSTemplateFormatVersion: "2010-09-09"
Description: AWS::S3::Bucket - {{ component_name }} - release

Resources:
  BucketS3UrlReleaseDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::ImportValue: {{ context.ResourceNamespace | d('core-network') }}:HostedZoneId
      Name:
        Fn::Sub:
          - "{{ names.release_dns_prefix }}.${RegionalHostedZoneName}"
          - RegionalHostedZoneName:
              Fn::ImportValue: {{ context.ResourceNamespace | d('core-network') }}:RegionalHostedZoneName
      ResourceRecords:
        - Fn::ImportValue:
            Fn::Sub: "{{ names.pointers_stack_name }}:BucketS3UrlDeploymentDns"
      Type: CNAME
      TTL: 60

Outputs:
  Build:
    Value: "{{ Build }}"

  BaseStackName:
    Value:
      Fn::ImportValue:
        Fn::Sub: "{{ names.pointers_stack_name }}:BaseStackName"

  PointersStackName:
    Value: "{{ names.pointers_stack_name }}"

  ResourcesStackName:
    Value:
      Fn::ImportValue:
        Fn::Sub: "{{ names.pointers_stack_name }}:ResourcesStackName"

  BucketS3UrlReleaseDns:
    Value:
      Ref: BucketS3UrlReleaseDnsRecord
