AWSTemplateFormatVersion: "2010-09-09"
Description: AWS::S3::Bucket - {{ component_name }} - security items

Conditions:
  Never: { "Fn::Equals": [ "1", "2" ] }

Resources:
  WaitConditionHandle:
    Condition: Never
    Type: AWS::CloudFormation::WaitConditionHandle

Outputs:
  DefaultExport:
    Value:
      Ref: AWS::StackName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:DefaultExport"
