AWSTemplateFormatVersion: "2010-09-09"
Description: AWS::VPCEndpoint - {{ component_name }} - security items

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: VPCE security group -   {{ component_name }} 
      VpcId:
        Fn::ImportValue: "core-network-{{ context.Environment }}-dmz:DmzVpc:VpcId"

  SecurityGroupExternal:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: VPCE External security group -  {{ component_name }}
      VpcId:
        Fn::ImportValue: "core-network-{{ context.Environment }}-dmz:DmzVpc:VpcId"

Outputs:
  DefaultExport:
    Value:
      Ref: AWS::StackName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:DefaultExport"

  SecurityGroupId:
    Value:
      Ref: SecurityGroup
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:SecurityGroupId"
  
  SecurityGroupExternalId:
    Value:
      Ref: SecurityGroupExternal
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:SecurityGroupExternalId"

  
