---
{% import "AWS/_shared/vars/names.j2" as names with context %}
{% set resource = app[component_name].Configuration.DBCluster %}

AWSTemplateFormatVersion: "2010-09-09"
Description: AWS::RDS::Aurora - {{ component_name }} - release

Resources:

  ReleaseDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::ImportValue: core-network:HostedZoneId
      Name:
        Fn::Sub:
          - "{{ names.release_dns_prefix }}.${RegionalHostedZoneName}"
          - RegionalHostedZoneName:
              Fn::ImportValue: core-network:RegionalHostedZoneName
      ResourceRecords:
        - !ImportValue "{{ names.pointers_stack_name }}:DeploymentDns"
      Type: CNAME
      TTL: 60

  ReleaseReaderDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue core-network:HostedZoneId
      Name:
        Fn::Sub:
          - "ro.{{ names.release_dns_prefix }}.${RegionalHostedZoneName}"
          - RegionalHostedZoneName:
              Fn::ImportValue: core-network:RegionalHostedZoneName
      ResourceRecords:
        - Fn::ImportValue:
            Fn::Sub: "{{ names.pointers_stack_name }}:DeploymentReaderDns"
      Type: CNAME
      TTL: 60

Outputs:

  Build:
    Value: "{{ context.Build }}"

  BaseStackName:
    Value: !ImportValue "{{ names.pointers_stack_name }}:BaseStackName"

  PointersStackName:
    Value: "{{ names.pointers_stack_name }}"

  ResourcesStackName:
    Value: !ImportValue "{{ names.pointers_stack_name }}:ResourcesStackName"

  ReleaseDns:
    Value: !Ref ReleaseDnsRecord

  ReleaseReaderDns:
    Value: !Ref ReleaseReaderDnsRecord
