AWS::ApplicationLoadBalancerV2:
  _Type: Component

  Configuration:

    ApplicationLoadBalancer:
      Pipeline::Security:
        _Type: Pipeline::IpSecurity
      Properties:
        Scheme:
          _Type: string
          _StringEnum: [ internal, internet-facing ]

    Listener:
      _KeyRegex: ".*Listener"
      _KeyCardinality: 0-100
      _Type: Resource::AWS::ElasticLoadBalancingV2::Listener::ALB

    ListenerCertificate:
      _KeyRegex: ".*ListenerCertificate"
      _KeyCardinality: 0-100
      _Type: Resource::AWS::ElasticLoadBalancingV2::ListenerCertificate
    
    ListenerRule:
      _KeyRegex: ".*ListenerRule"
      _KeyCardinality: 0-100
      _Type: Resource::AWS::ElasticLoadBalancingV2::ListenerRule

    TargetGroup:
      _KeyRegex: ".*TargetGroup"
      _KeyCardinality: 0-100
      Properties:
        Name:
          _Type: string
          _Required: false
        HealthCheckIntervalSeconds:
          _Type: int
          _Required: false
          _IntMinValue: 5
          _IntMaxValue: 300
        HealthCheckPath:
          _Type: string
          _Required: false
          _StringLength: 1-1024
        HealthCheckPort:
          _Type: scalar
          _Required: false
        HealthCheckProtocol:
          _Type: string
          _Required: false
          _StringEnum: [ HTTP, HTTPS ]
        HealthCheckTimeoutSeconds:
          _Type: int
          _Required: false
          _IntMinValue: 2
          _IntMaxValue: 60
        HealthyThresholdCount:
          _Type: int
          _Required: false
          _IntMinValue: 2
          _IntMaxValue: 10
        Matcher:
          _Required: false
          _Documentation: https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_Matcher.html
          HttpCode:
            _Type: string
            _Documentation: https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_Matcher.html
            _StringRegex: '([2-4][0-9]{2}(,[2-4][0-9]{2})*)|([2-4][0-9]{2}-[2-4][0-9]{2})'
        Port:
          _Type: int
        Protocol:
          _Type: string
          _StringEnum: [ HTTP, HTTPS ]
        TargetGroupAttributes:
          _Type: list
          _Required: false
          _ListItemSpec:
            Key:
              _Type: string
              _StringEnum: [ deregistration_delay.timeout_seconds, stickiness.enabled, stickiness.type, stickiness.lb_cookie.duration_seconds ]
              _StringLength: 1-256
              _StringRegex: '[a-zA-Z0-9._]+'
            Value:
              _Type: scalar
        Targets:
          _Type: list
          _Required: false
          _ListLength: 1+
          _ListItemSpec:
            Id:
              _Type: string
              _StringLength: 1-256
              _StringRegex: '[a-zA-Z0-9_.-]+'
        TargetType:
          _Type: string
          _Required: false
          _StringEnum: [ instance,ip,lambda ]
        UnhealthyThresholdCount:
          _Type: int
          _Required: false
          _IntMinValue: 2
          _IntMaxValue: 10
