AWSTemplateFormatVersion: "2010-09-09"
Description: AWS::EFS - {{ component_name }} - security items

Resources:

  # Used by MountTarget resources.
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Mount Targets Security Group
      VpcId:
        Fn::ImportValue: "{{ context.ResourceNamespace | d('core-network') }}:{{ context.VpcAliases['private'] }}:VpcId"

Outputs:

  DefaultExport:
    Value:
      Ref: AWS::StackName
    Export:
      Name: !Sub "${AWS::StackName}:DefaultExport"

  SecurityGroupId:
    Value: !Ref SecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}:SecurityGroupId"
