AWSTemplateFormatVersion: "2010-09-09"
Description: AWS::EFS - {{ component_name }} - security rules

Parameters:

  # TODO Unused params documented where?

  KmsKeyArn:
    Type: String
    Default: ""

  ResourcesStackName:
    Type: String
    Default: ""

  SecurityStackName:
    Type: String

  Stage:
    Type: String
    Default: "final"

Resources:

  DefaultImport:
    Metadata:
      DefaultImport:
        Fn::ImportValue:
          Fn::Sub: "${SecurityStackName}:DefaultExport"
    Type: AWS::CloudFormation::WaitConditionHandle

  # 2049 for EFS - can make explicit?
  {% for rule in app[component_name].Configuration.FileSystem | ip_rules %}
  IpRule{{ loop.index }}:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "{{ rule.Description }}"
      GroupId:
        Fn::ImportValue:
          Fn::Sub: ${SecurityStackName}:SecurityGroupId
      IpProtocol: {{ rule.Protocol }}
      FromPort: {{ rule.FromPort }}
      ToPort: {{ rule.ToPort }}
      {% if rule.Type == 'cidr' %}
      CidrIp: "{{ rule.Value }}"
      {% else %}
      SourceSecurityGroupId:
        Fn::ImportValue: "{{ rule.Value }}"
      {% endif %}
  {% endfor %}

  # TODO IamPolicy statements requried? See consumables/AWS/S3/Bucket/files/security-rules.yaml for an example.
