{% import "AWS/_shared/vars/names.j2" as names with context %}
{% set Build = context.Build %}
{% if 'PersistUpdateVersion' in app[component_name] %}
{% set Build = app[component_name].PersistUpdateVersion %}
{% endif %}

AWSTemplateFormatVersion: "2010-09-09"
Description: AWS::ElastiCache::Redis - {{ component_name }} - release

Resources:

  {% set resource = app[component_name].Configuration.ReplicationGroup %}
  ReleaseDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue {{ context.ResourceNamespace | d('core-network') }}:HostedZoneId
      Name:
        Fn::Sub:
          - "{{ names.release_dns_prefix }}.${RegionalHostedZoneName}"
          - RegionalHostedZoneName: !ImportValue {{ context.ResourceNamespace | d('core-network') }}:RegionalHostedZoneName
      ResourceRecords:
        - !ImportValue "{{ names.pointers_stack_name }}:DeploymentDns"
      Type: CNAME
      TTL: 60

  {% if resource.Properties.NumNodeGroups == 1 %}
  ReaderReleaseDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Fn::ImportValue: {{ context.ResourceNamespace | d('core-network') }}:HostedZoneId
      Name:
        Fn::Sub:
          - "reader-{{ names.release_dns_prefix }}.${RegionalHostedZoneName}"
          - RegionalHostedZoneName: !ImportValue {{ context.ResourceNamespace | d('core-network') }}:RegionalHostedZoneName
      ResourceRecords:
        - !ImportValue "{{ names.pointers_stack_name }}:ReaderDeploymentDns"
      Type: CNAME
      TTL: 60
  {% endif %}

Outputs:

  Build:
    Value: "{{ Build }}"

  BaseStackName:
    Value:
      Fn::ImportValue: "{{ names.pointers_stack_name }}:BaseStackName"

  PointersStackName:
    Value: "{{ names.pointers_stack_name }}"

  ResourcesStackName:
    Value:
      Fn::ImportValue: "{{ names.pointers_stack_name }}:ResourcesStackName"

  ReleaseDns:
    Value: !Ref ReleaseDnsRecord

  {% if resource.Properties.NumNodeGroups == 1 %}
  ReaderReleaseDns:
    Value: !Ref ReaderReleaseDnsRecord
  {% endif %}
