AWSTemplateFormatVersion: "2010-09-09"
Description: AWS::DynamoDB - {{ component_name }} - security rules

Parameters:
  KmsKeyArn:
    Type: String
    Default: ""

  ResourcesStackName:
    Type: String
    Default: ""

  SecurityStackName:
    Type: String

  Stage:
    Type: String
    Default: "final"

Conditions:
  FinalStage: { "Fn::Equals": [ Ref: Stage, "final" ] }

Resources:
  DefaultImport:
    Metadata:
      DefaultImport:
        Fn::ImportValue:
          Fn::Sub: "${SecurityStackName}:DefaultExport"
    Type: AWS::CloudFormation::WaitConditionHandle

  {% for rule in app[component_name].Configuration.Table | iam_rules %}
  IamPolicy{{ loop.index }}:
    Type: AWS::IAM::Policy
    Condition: FinalStage
    Properties:
      PolicyName: {{ component_name }}-{{ context.Build }}-x{{ loop.index }}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              {% if 'read' in rule.Allow %}
              - dynamodb:BatchGetItem
              - dynamodb:Describe*
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
              {% endif %}
              {% if 'write' in rule.Allow %}
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              {% endif %}
              {% if 'delete' in rule.Allow %}
              - dynamodb:DeleteItem
              {% endif %}
            Resource:
              - Fn::ImportValue:
                  Fn::Sub: "${ResourcesStackName}:TableArn"
              - Fn::Sub:
                - "${TableArn}/*"
                - TableArn:
                    Fn::ImportValue:
                      Fn::Sub: "${ResourcesStackName}:TableArn"
      Roles:
        - Fn::ImportValue: "{{ rule.Value }}"   # {{ rule.Description }}

  {% endfor %}
