{% import "AWS/_shared/vars/names.j2" as names with context %}

# CLB/ALB suppport.
{% set config = app[component_name].Configuration %}
{% set load_balancer = config.get('LoadBalancer', config.get('ApplicationLoadBalancer')) %}

AWSTemplateFormatVersion: "2010-09-09"
Description: AWS::AutoScale - {{ component_name }} - pointers

Parameters:
  BaseStackName:
    Type: String

  ResourcesStackName:
    Type: String

Resources:
  # Private Deployment DNS
  PrivateDeploymentDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName:
          Fn::ImportValue:
            Fn::Sub: "${ResourcesStackName}:LoadBalancerDnsName"
        EvaluateTargetHealth: false
        HostedZoneId:
          Fn::ImportValue:
            Fn::Sub: "${ResourcesStackName}:LoadBalancerHostedZoneId"
      HostedZoneId:
        Fn::ImportValue: {{ context.ResourceNamespace | d('core-network') }}:HostedZoneId
      Name:
        Fn::Sub:
          - "{{ names.deployment_dns_prefix_hyphen }}.${RegionalHostedZoneName}"
          - RegionalHostedZoneName:
              Fn::ImportValue: {{ context.ResourceNamespace | d('core-network') }}:RegionalHostedZoneName
      Type: A

  {% if (load_balancer.Properties.Scheme | d('internal')) == 'internet-facing' %}
  # Public Deployment DNS
  PublicDeploymentDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName:
          Fn::ImportValue:
            Fn::Sub: "${ResourcesStackName}:LoadBalancerDnsName"
        EvaluateTargetHealth: false
        HostedZoneId:
          Fn::ImportValue:
            Fn::Sub: "${ResourcesStackName}:LoadBalancerHostedZoneId"
      HostedZoneId:
        Fn::ImportValue: {{ context.ResourceNamespace | d('core-network') }}:PublicOnlyHostedZoneId
      Name:
        Fn::Sub:
          - "{{ names.deployment_dns_prefix_hyphen }}.${PublicOnlyRegionalHostedZoneName}"
          - PublicOnlyRegionalHostedZoneName:
              Fn::ImportValue: {{ context.ResourceNamespace | d('core-network') }}:PublicOnlyRegionalHostedZoneName
      Type: A
  {% endif %}

Outputs:
  Build:
    Value: "{{ context.Build }}"
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:Build"

  BaseStackName:
    Value:
      Ref: BaseStackName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:BaseStackName"

  PointersStackName:
    Value:
      Ref: "AWS::StackName"
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:PointersStackName"

  ResourcesStackName:
    Value:
      Ref: ResourcesStackName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:ResourcesStackName"

  PrivateDeploymentDns:
    Value:
      Ref: PrivateDeploymentDnsRecord
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:PrivateDeploymentDns"

  PublicDeploymentDns:
    Value:
      {% if (load_balancer.Properties.Scheme | d('internal')) == 'internet-facing' %}
      Ref: PublicDeploymentDnsRecord
      {% else %}
      "none"
      {% endif %}
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:PublicDeploymentDns"

  LoadBalancerName:
    Value:
      Fn::ImportValue:
        Fn::Sub: "${ResourcesStackName}:LoadBalancerName"
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:LoadBalancerName"
