AWSTemplateFormatVersion: "2010-09-09"
Description: AWS::SQS::Queue - {{ component_name }} - security items

Resources:
  WaitConditionHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

Outputs:
  DefaultExport:
    Value:
      Ref: AWS::StackName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:DefaultExport"
