AWSTemplateFormatVersion: "2010-09-09"
Description: AWS::MSK - {{ component_name }} - security items

Resources:
  # Application autoscaling role
  MSKSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: MSK security group
      VpcId:
        Fn::ImportValue: "{{ context.ResourceNamespace | d('core-network') }}:{{ context.VpcAliases['private'] }}:VpcId"

Outputs:
  DefaultExport:
    Value:
      Ref: AWS::StackName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:DefaultExport"

  MSKSecurityGroupId:
    Value:
      Ref: MSKSecurityGroup
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}:MSKSecurityGroupId"
